env: "local" # local, dev, prod
# storage_path: "/smt" - this is path to file where is stored DB (for SQLite case)
http_server:
  address: "localhost:8080"
  timeout: 4s # timeout for processing a request: time for reading request and same time for sending response
  idle_timeout: 60s # time of life a connection by client